CREATE TABLE TAGS (id BIGINT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, CONSTRAINT PK_TAGS PRIMARY KEY (id));

ALTER TABLE TAGS ADD CONSTRAINT tag_name UNIQUE (name);


CREATE TABLE SENDERS (id BIGINT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, CONSTRAINT PK_SENDERS PRIMARY KEY (id));

ALTER TABLE SENDERS ADD CONSTRAINT sender_name UNIQUE (name);


CREATE TABLE UPLOADS (id CHAR(36) NOT NULL, filename NVARCHAR(255) NOT NULL, mimetype NVARCHAR(255) NOT NULL, created datetime DEFAULT NOW() NOT NULL, CONSTRAINT PK_UPLOADS PRIMARY KEY (id));