CREATE TABLE TAGS (id BIGINT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, CONSTRAINT PK_TAGS PRIMARY KEY (id));

ALTER TABLE TAGS ADD CONSTRAINT tag_name UNIQUE (name);


CREATE TABLE SENDERS (id BIGINT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, CONSTRAINT PK_SENDERS PRIMARY KEY (id));

ALTER TABLE SENDERS ADD CONSTRAINT sender_name UNIQUE (name);


CREATE TABLE UPLOADS (id CHAR(36) NOT NULL, filename NVARCHAR(255) NOT NULL, mimetype NVARCHAR(255) NOT NULL, created datetime DEFAULT NOW() NOT NULL, CONSTRAINT PK_UPLOADS PRIMARY KEY (id));

CREATE TABLE DOCUMENTS (id CHAR(36) NOT NULL, title NVARCHAR(255) NOT NULL, filename NVARCHAR(255) NOT NULL, alternativeid VARCHAR(128) NULL, previewlink VARCHAR(128) NULL, amount numeric NULL, created datetime DEFAULT NOW() NOT NULL, modified datetime NULL, taglist TEXT NULL, senderlist TEXT NULL, CONSTRAINT PK_DOCUMENTS PRIMARY KEY (id));

ALTER TABLE DOCUMENTS ADD CONSTRAINT alternativeid_unique UNIQUE (alternativeid);
