## jwt security settings
auth:
  cookieName: login_token
  tokenSecret: ${MYDMS_JWT_TOKEN_SECRET:secret}
  tokenIssuer: login.binggl.net
  tokenSubject: login.User
  name: mydms
  url: https://mydms.binggl.net/
  loginUrl: https://login.binggl.net/auth/flow?~site=mydms&~url=http://devel.binggl.net:8080/

application:
  security:
    # define the path for CORS - allowed from
    cors: http://devel.binggl.net:8080/
    # secret key for hashing operations
    secret: 12345678
    # roles allowed to access swagger-ui
    swagger: User, Admin
  # the url used to redirect for /
  url: http://devel.binggl.net:8080/app/index.html
  detailedErrors: ${MYDMS_DETAILED_ERRORS:false}
  # upload settings
  upload:
    maxUploadSize: 512000
    allowedFileTypes:
      - application/pdf
      - image/jpeg
      - image/png
      - image/gif
    uploadPath: ${MYDMS_TMP_PATH:-/tmp}

google:
  clientId: ${MYDMS_GOOGLE_CLIENT_ID:-}
  clientSecret: ${MYDMS_GOOGLE_CLIENT_SECRET:-}
  redirectUrl: ${MYDMS_GOOGLE_REDIRECT_URL:/}
  encryptionKey: ${MYDMS_GOOGLE_ENCRYPTION_KEY:-}
  storePath: ${MYDMS_TMP_PATH:-/tmp}
  parentDrivePath: ${MYDMS_GOOGLE_DRIVE_PARENT_ID:-}
  successUrl: /

---
spring:
  profiles: rest

  application:
    name: mydms
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${MYDMS_DB_HOST}:3307/mydms-test
    username: ${MYDMS_DB_USER:mydms}
    password: ${MYDMS_DB_PASS:mydms}



